<?php


$_MAG_DATA['get_localization'] = [];
$_MAG_DATA['get_localization']['weather_comfort'] = 'Comfort';
$_MAG_DATA['get_localization']['weather_pressure'] = 'Pressure';
$_MAG_DATA['get_localization']['weather_mmhg'] = 'mm Hg';
$_MAG_DATA['get_localization']['weather_wind'] = 'Wind';
$_MAG_DATA['get_localization']['weather_speed'] = 'm/s';
$_MAG_DATA['get_localization']['weather_humidity'] = 'Humidity';
$_MAG_DATA['get_localization']['current_weather_unavailable'] = 'Current weather unavailable';
$_MAG_DATA['get_localization']['current_weather_not_configured'] = 'The weather is not configured';
$_MAG_DATA['get_localization']['karaoke_view'] = 'VIEW';
$_MAG_DATA['get_localization']['karaoke_sort'] = 'SORT';
$_MAG_DATA['get_localization']['karaoke_search'] = 'SEARCH';
$_MAG_DATA['get_localization']['karaoke_sampling'] = 'PICKING';
$_MAG_DATA['get_localization']['karaoke_by_letter'] = 'BY LETTER';
$_MAG_DATA['get_localization']['karaoke_by_performer'] = 'BY NAME';
$_MAG_DATA['get_localization']['karaoke_by_title'] = 'BY TITLE';
$_MAG_DATA['get_localization']['karaoke_title'] = 'KARAOKE';
$_MAG_DATA['get_localization']['layer_page'] = 'PAGE';
$_MAG_DATA['get_localization']['layer_from'] = 'OF';
$_MAG_DATA['get_localization']['layer_found'] = 'FOUND';
$_MAG_DATA['get_localization']['layer_records'] = 'RECORDINGS';
$_MAG_DATA['get_localization']['layer_loading'] = 'LOADING...';
$_MAG_DATA['get_localization']['Loading...'] = 'Loading...';
$_MAG_DATA['get_localization']['mbrowser_title'] = 'Media Browser';
$_MAG_DATA['get_localization']['mbrowser_connected'] = 'connected';
$_MAG_DATA['get_localization']['mbrowser_disconnected'] = 'disconnected';
$_MAG_DATA['get_localization']['mbrowser_not_found'] = 'not found';
$_MAG_DATA['get_localization']['usb_drive'] = 'USB drive';
$_MAG_DATA['get_localization']['player_limit_notice'] = 'The number of connections is limited. <br> Try again later';
$_MAG_DATA['get_localization']['player_file_missing'] = 'File missing';
$_MAG_DATA['get_localization']['player_server_error'] = 'Server error';
$_MAG_DATA['get_localization']['player_access_denied'] = 'Access denied';
$_MAG_DATA['get_localization']['player_server_unavailable'] = 'Server unavailable';
$_MAG_DATA['get_localization']['player_series'] = 'part';
$_MAG_DATA['get_localization']['player_track'] = 'Track';
$_MAG_DATA['get_localization']['player_off'] = 'Off';
$_MAG_DATA['get_localization']['player_subtitle'] = 'Subtitles';
$_MAG_DATA['get_localization']['player_claim'] = 'Complain';
$_MAG_DATA['get_localization']['player_on_sound'] = 'on sound';
$_MAG_DATA['get_localization']['player_on_video'] = 'on video';
$_MAG_DATA['get_localization']['player_audio'] = 'Audio';
$_MAG_DATA['get_localization']['player_ty'] = 'Thank you, your opinion will be taken into account';
$_MAG_DATA['get_localization']['series_by_one_play'] = 'one series';
$_MAG_DATA['get_localization']['series_continuously_play'] = 'continuously';
$_MAG_DATA['get_localization']['aspect_fit'] = 'fit on';
$_MAG_DATA['get_localization']['aspect_big'] = 'zoom';
$_MAG_DATA['get_localization']['aspect_opt'] = 'optimal';
$_MAG_DATA['get_localization']['aspect_exp'] = 'stretch';
$_MAG_DATA['get_localization']['aspect_cmb'] = 'combined';
$_MAG_DATA['get_localization']['radio_title'] = 'RADIO';
$_MAG_DATA['get_localization']['radio_sort'] = 'SORT';
$_MAG_DATA['get_localization']['radio_favorite'] = 'FAVORITE';
$_MAG_DATA['get_localization']['radio_search'] = 'SEARCH';
$_MAG_DATA['get_localization']['radio_by_number'] = 'by number';
$_MAG_DATA['get_localization']['radio_by_title'] = 'by title';
$_MAG_DATA['get_localization']['radio_only_favorite'] = 'only favorite';
$_MAG_DATA['get_localization']['radio_fav_add'] = 'add';
$_MAG_DATA['get_localization']['radio_fav_del'] = 'del';
$_MAG_DATA['get_localization']['radio_search_box'] = 'SEARCH';
$_MAG_DATA['get_localization']['tv_view'] = 'VIEW';
$_MAG_DATA['get_localization']['tv_sort'] = 'SORT';
$_MAG_DATA['get_localization']['favorite'] = 'FAVORITE';
$_MAG_DATA['get_localization']['tv_favorite'] = 'FAVORITE';
$_MAG_DATA['get_localization']['tv_move'] = 'MOVE';
$_MAG_DATA['get_localization']['tv_by_number'] = 'by number';
$_MAG_DATA['get_localization']['tv_by_title'] = 'by title';
$_MAG_DATA['get_localization']['tv_only_favorite'] = 'only favorite';
$_MAG_DATA['get_localization']['tv_only_hd'] = 'HD only';
$_MAG_DATA['get_localization']['tv_list'] = 'list';
$_MAG_DATA['get_localization']['tv_list_w_info'] = 'list + info';
$_MAG_DATA['get_localization']['tv_title'] = 'TV';
$_MAG_DATA['get_localization']['vclub_info'] = 'information about the movie';
$_MAG_DATA['get_localization']['vclub_year'] = 'Year';
$_MAG_DATA['get_localization']['vclub_country'] = 'Country';
$_MAG_DATA['get_localization']['vclub_genre'] = 'Genre';
$_MAG_DATA['get_localization']['vclub_length'] = 'Length';
$_MAG_DATA['get_localization']['vclub_minutes'] = 'min';
$_MAG_DATA['get_localization']['vclub_director'] = 'Director';
$_MAG_DATA['get_localization']['vclub_cast'] = 'Cast';
$_MAG_DATA['get_localization']['vclub_rating'] = 'Rating';
$_MAG_DATA['get_localization']['vclub_age'] = 'Age';
$_MAG_DATA['get_localization']['vclub_rating_mpaa'] = 'Rating MPAA';
$_MAG_DATA['get_localization']['vclub_view'] = 'VIEW';
$_MAG_DATA['get_localization']['vclub_sort'] = 'SORT';
$_MAG_DATA['get_localization']['vclub_search'] = 'SEARCH';
$_MAG_DATA['get_localization']['vclub_fav'] = 'FAVORITE';
$_MAG_DATA['get_localization']['vclub_other'] = 'OTHER';
$_MAG_DATA['get_localization']['vclub_find'] = 'FIND';
$_MAG_DATA['get_localization']['vclub_by_letter'] = 'BY LETTER';
$_MAG_DATA['get_localization']['vclub_by_genre'] = 'BY GENRE';
$_MAG_DATA['get_localization']['vclub_by_year'] = 'BY YEAR';
$_MAG_DATA['get_localization']['vclub_by_rating'] = 'BY RATING';
$_MAG_DATA['get_localization']['vclub_search_box'] = 'search';
$_MAG_DATA['get_localization']['vclub_query_box'] = 'picking';
$_MAG_DATA['get_localization']['vclub_by_title'] = 'by title';
$_MAG_DATA['get_localization']['vclub_by_addtime'] = 'by addtime';
$_MAG_DATA['get_localization']['vclub_top'] = 'rating';
$_MAG_DATA['get_localization']['vclub_only_hd'] = 'HD only';
$_MAG_DATA['get_localization']['vclub_only_favorite'] = 'favorite only';
$_MAG_DATA['get_localization']['vclub_only_purchased'] = 'purchased';
$_MAG_DATA['get_localization']['vclub_not_ended'] = 'not ended';
$_MAG_DATA['get_localization']['vclub_list'] = 'list';
$_MAG_DATA['get_localization']['vclub_list_w_info'] = 'list + info';
$_MAG_DATA['get_localization']['vclub_title'] = 'VIDEOCLUB';
$_MAG_DATA['get_localization']['vclub_purchased'] = 'Purchased';
$_MAG_DATA['get_localization']['vclub_rent_expires_in'] = 'rent expires in';
$_MAG_DATA['get_localization']['cut_off_msg'] = 'Your STB is blocked.<br/> Call the provider.';
$_MAG_DATA['get_localization']['month_arr'] = ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'];
$_MAG_DATA['get_localization']['week_arr'] = ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'];
$_MAG_DATA['get_localization']['year'] = '';
$_MAG_DATA['get_localization']['records_title'] = 'RECORDINGS';
$_MAG_DATA['get_localization']['ears_back'] = '<br>B<br>A<br>C<br>K<br>';
$_MAG_DATA['get_localization']['ears_about_movie'] = '<br>A<br>B<br>O<br>U<br>T<br> <br>M<br>O<br>V<br>I<br>E<br>';
$_MAG_DATA['get_localization']['ears_tv_guide'] = '<br>T<br>V<br> <br>G<br>U<br>I<br>D<br>E<br>';
$_MAG_DATA['get_localization']['ears_about_package'] = '<br>P<br>A<br>C<br>K<br>A<br>G<br>E<br> <br>I<br>N<br>F<br>O<br>';
$_MAG_DATA['get_localization']['settings_title'] = 'SETTINGS';
$_MAG_DATA['get_localization']['parent_settings_cancel'] = 'CANCEL';
$_MAG_DATA['get_localization']['parent_settings_save'] = 'SAVE';
$_MAG_DATA['get_localization']['parent_settings_old_pass'] = 'Current password';
$_MAG_DATA['get_localization']['parent_settings_title'] = 'PARENTAL SETTINGS';
$_MAG_DATA['get_localization']['parent_settings_title_short'] = 'PARENTAL';
$_MAG_DATA['get_localization']['parent_settings_new_pass'] = 'New password';
$_MAG_DATA['get_localization']['parent_settings_repeat_new_pass'] = 'Repeat new password';
$_MAG_DATA['get_localization']['settings_saved'] = 'Settings saved';
$_MAG_DATA['get_localization']['settings_saved_reboot'] = 'Settings saved.<br>The STB will be rebooted. Press OK.';
$_MAG_DATA['get_localization']['settings_check_error'] = 'Error filling fields';
$_MAG_DATA['get_localization']['settings_saving_error'] = 'Saving error';
$_MAG_DATA['get_localization']['localization_settings_title'] = 'LOCALIZATION';
$_MAG_DATA['get_localization']['localization_label'] = 'Language of the interface';
$_MAG_DATA['get_localization']['country_label'] = 'Country';
$_MAG_DATA['get_localization']['city_label'] = 'City';
$_MAG_DATA['get_localization']['localization_page_button_info'] = 'Use PAGE-/+ buttons to move through several menu items';
$_MAG_DATA['get_localization']['settings_software_update'] = 'SOFTWARE UPDATE';
$_MAG_DATA['get_localization']['update_settings_cancel'] = 'CANCEL';
$_MAG_DATA['get_localization']['update_settings_start_update'] = 'START UPDATE';
$_MAG_DATA['get_localization']['update_from_http'] = 'From HTTP';
$_MAG_DATA['get_localization']['update_from_usb'] = 'From USB';
$_MAG_DATA['get_localization']['update_source'] = 'Source';
$_MAG_DATA['get_localization']['update_method_select'] = 'Method select';
$_MAG_DATA['get_localization']['empty'] = 'EMPTY';
$_MAG_DATA['get_localization']['course_title'] = 'Exchange rate on';
$_MAG_DATA['get_localization']['course_title_nbu'] = 'NBU exchange rate on';
$_MAG_DATA['get_localization']['course_title_cbr'] = 'CBR exchange rate on';
$_MAG_DATA['get_localization']['dayweather_title'] = 'WEATHER';
$_MAG_DATA['get_localization']['dayweather_pressure'] = 'pres.:';
$_MAG_DATA['get_localization']['dayweather_mmhg'] = 'mm Hg';
$_MAG_DATA['get_localization']['dayweather_wind'] = 'wind:';
$_MAG_DATA['get_localization']['dayweather_speed'] = 'm/s';
$_MAG_DATA['get_localization']['infoportal_title'] = 'INFOPORTAL';
$_MAG_DATA['get_localization']['cityinfo_title'] = 'CITY INFO';
$_MAG_DATA['get_localization']['cityinfo_main'] = 'emergency';
$_MAG_DATA['get_localization']['cityinfo_help'] = 'help';
$_MAG_DATA['get_localization']['cityinfo_other'] = 'other';
$_MAG_DATA['get_localization']['cityinfo_sort'] = 'VIEW';
$_MAG_DATA['get_localization']['horoscope_title'] = 'HOROSCOPE';
$_MAG_DATA['get_localization']['anecdote_title'] = 'JOKES';
$_MAG_DATA['get_localization']['anecdote_goto'] = 'GOTO';
$_MAG_DATA['get_localization']['anecdote_like'] = 'LIKE';
$_MAG_DATA['get_localization']['anecdote_bookmark'] = 'BOOKMARK';
$_MAG_DATA['get_localization']['anecdote_to_bookmark'] = 'TO BOOKMARK';
$_MAG_DATA['get_localization']['anecdote_pagebar_title'] = 'JOKE';
$_MAG_DATA['get_localization']['mastermind_title'] = 'MASTERMIND';
$_MAG_DATA['get_localization']['mastermind_rules'] = 'RULES';
$_MAG_DATA['get_localization']['mastermind_rating'] = 'RATING';
$_MAG_DATA['get_localization']['mastermind_bull'] = 'B';
$_MAG_DATA['get_localization']['mastermind_cow'] = 'C';
$_MAG_DATA['get_localization']['mastermind_rules_text'] = 'Your task is to guess the number of unduplicated four digits, the first of them - not zero. Every your guess will be compared with the number put forth a STB. If you guessed a digit, but it is not in place, then it is a COW (C). If you guessed, and a number, and its location, this BULL (B).';
$_MAG_DATA['get_localization']['mastermind_move_cursor'] = 'Moving the cursor';
$_MAG_DATA['get_localization']['mastermind_cell_numbers'] = 'Enter numbers into cells';
$_MAG_DATA['get_localization']['mastermind_step_confirmation'] = 'Confirmation of the step';
$_MAG_DATA['get_localization']['mastermind_page'] = 'Page';
$_MAG_DATA['get_localization']['mastermind_history_moves'] = 'Moving through the pages of history moves';
$_MAG_DATA['get_localization']['msg_service_off'] = 'Service is disabled';
$_MAG_DATA['get_localization']['msg_channel_not_available'] = 'Channel is not available';
$_MAG_DATA['get_localization']['epg_title'] = 'TV Guide';
$_MAG_DATA['get_localization']['epg_record'] = 'RECORD';
$_MAG_DATA['get_localization']['epg_remind'] = 'REMIND';
$_MAG_DATA['get_localization']['epg_memo'] = 'Memo';
$_MAG_DATA['get_localization']['epg_goto_ch'] = 'Goto channel';
$_MAG_DATA['get_localization']['epg_close_msg'] = 'Close';
$_MAG_DATA['get_localization']['epg_on_ch'] = 'on channel';
$_MAG_DATA['get_localization']['epg_now_begins'] = 'now begins';
$_MAG_DATA['get_localization']['epg_on_time'] = 'in';
$_MAG_DATA['get_localization']['epg_started'] = 'started';
$_MAG_DATA['get_localization']['epg_more'] = 'MORE';
$_MAG_DATA['get_localization']['epg_category'] = 'Category';
$_MAG_DATA['get_localization']['epg_director'] = 'Director';
$_MAG_DATA['get_localization']['epg_actors'] = 'Actors';
$_MAG_DATA['get_localization']['epg_desc'] = 'Description';
$_MAG_DATA['get_localization']['search_box_languages'] = ['en'];
$_MAG_DATA['get_localization']['date_format'] = '{0}, {2} {1}, {3}';
$_MAG_DATA['get_localization']['time_format'] = '{2}:{1} {3}';
$_MAG_DATA['get_localization']['timezone_label'] = 'Timezone';
$_MAG_DATA['get_localization']['ntp_server'] = 'NTP Server';
$_MAG_DATA['get_localization']['remote_pvr_del'] = 'DELETE';
$_MAG_DATA['get_localization']['remote_pvr_stop'] = 'STOP';
$_MAG_DATA['get_localization']['remote_pvr_del_confirm'] = 'Do you really want to delete this record?';
$_MAG_DATA['get_localization']['remote_pvr_stop_confirm'] = 'Do you really want to stop this record?';
$_MAG_DATA['get_localization']['alert_confirm'] = 'Confirm';
$_MAG_DATA['get_localization']['alert_cancel'] = 'Cancel';
$_MAG_DATA['get_localization']['recorder_server_error'] = 'Server error. Try again later.';
$_MAG_DATA['get_localization']['record_duration'] = 'RECORDING DURATION, h';
$_MAG_DATA['get_localization']['rest_length_title'] = 'FREE on the server, h';
$_MAG_DATA['get_localization']['channel_recording_restricted'] = 'Recording this channel is forbidden';
$_MAG_DATA['get_localization']['playback_settings_buffer_size'] = 'Buffer size';
$_MAG_DATA['get_localization']['playback_settings_time'] = 'Time, sec';
$_MAG_DATA['get_localization']['playback_settings_title'] = 'PLAYBACK';
$_MAG_DATA['get_localization']['cancel_btn'] = 'CANCEL';
$_MAG_DATA['get_localization']['settings_cancel'] = 'CANCEL';
$_MAG_DATA['get_localization']['playback_settings_cancel'] = 'CANCEL';
$_MAG_DATA['get_localization']['exit_btn'] = 'EXIT';
$_MAG_DATA['get_localization']['yes_btn'] = 'YES';
$_MAG_DATA['get_localization']['close_btn'] = 'CLOSE';
$_MAG_DATA['get_localization']['ok_btn'] = 'OK';
$_MAG_DATA['get_localization']['pay_btn'] = 'PAY';
$_MAG_DATA['get_localization']['play_btn'] = 'PLAY';
$_MAG_DATA['get_localization']['start_btn'] = 'START';
$_MAG_DATA['get_localization']['add_btn'] = 'ADD';
$_MAG_DATA['get_localization']['settings_save'] = 'SAVE';
$_MAG_DATA['get_localization']['playback_settings_save'] = 'SAVE';
$_MAG_DATA['get_localization']['audio_out'] = 'Audio out';
$_MAG_DATA['get_localization']['audio_out_analog'] = 'Analog only';
$_MAG_DATA['get_localization']['audio_out_analog_spdif'] = 'Analog and S/PDIF 2-channel PCM';
$_MAG_DATA['get_localization']['audio_out_spdif'] = 'S/PDIF raw or 2-channel PCM';
$_MAG_DATA['get_localization']['game'] = 'GAME';
$_MAG_DATA['get_localization']['downloads_title'] = 'DOWNLOADS';
$_MAG_DATA['get_localization']['not_found_mounted_devices'] = 'Not found mounted devices';
$_MAG_DATA['get_localization']['downloads_add_download'] = 'Add download';
$_MAG_DATA['get_localization']['downloads_device'] = 'Device';
$_MAG_DATA['get_localization']['downloads_file_name'] = 'File name';
$_MAG_DATA['get_localization']['downloads_ok'] = 'Ok';
$_MAG_DATA['get_localization']['downloads_cancel'] = 'Cancel';
$_MAG_DATA['get_localization']['downloads_create'] = 'CREATE';
$_MAG_DATA['get_localization']['downloads_move_up'] = 'MOVE UP';
$_MAG_DATA['get_localization']['downloads_move_down'] = 'MOVE DOWN';
$_MAG_DATA['get_localization']['downloads_delete'] = 'DELETE';
$_MAG_DATA['get_localization']['downloads_record'] = 'RECORDING';
$_MAG_DATA['get_localization']['downloads_download'] = 'DOWNLOAD';
$_MAG_DATA['get_localization']['downloads_record_and_file'] = 'RECORDING AND FILE';
$_MAG_DATA['get_localization']['playback_limit_title'] = 'Duration of continuous playback';
$_MAG_DATA['get_localization']['playback_limit_off'] = 'Without limit';
$_MAG_DATA['get_localization']['playback_hours'] = 'hours';
$_MAG_DATA['get_localization']['playback_limit_reached'] = 'Reached limit the duration of continuous playback. To continue playback, press the OK or EXIT.';
$_MAG_DATA['get_localization']['common_settings_title'] = 'GENERAL';
$_MAG_DATA['get_localization']['screensaver_delay_title'] = 'Screensaver interval';
$_MAG_DATA['get_localization']['screensaver_off'] = 'Disabled';
$_MAG_DATA['get_localization']['screensaver_minutes'] = 'min';
$_MAG_DATA['get_localization']['demo_video_title'] = 'DEMO VIDEO';
$_MAG_DATA['get_localization']['account_info_title'] = 'ACCOUNT';
$_MAG_DATA['get_localization']['coming_soon'] = 'Coming soon';
$_MAG_DATA['get_localization']['account_info'] = 'INFORMATION';
$_MAG_DATA['get_localization']['account_payment'] = 'PAYMENT';
$_MAG_DATA['get_localization']['account_pay'] = 'PAY';
$_MAG_DATA['get_localization']['account_agreement'] = 'AGREEMENT';
$_MAG_DATA['get_localization']['account_terms'] = 'TERMS OF USE';
$_MAG_DATA['get_localization']['demo_video'] = 'Video instruction';
$_MAG_DATA['get_localization']['tv_quality'] = 'QUALITY';
$_MAG_DATA['get_localization']['tv_quality_low'] = 'low';
$_MAG_DATA['get_localization']['tv_quality_medium'] = 'medium';
$_MAG_DATA['get_localization']['tv_quality_high'] = 'high';
$_MAG_DATA['get_localization']['tv_fav_add'] = 'add';
$_MAG_DATA['get_localization']['tv_fav_del'] = 'del';
$_MAG_DATA['get_localization']['internet'] = 'internet';
$_MAG_DATA['get_localization']['network_status_title'] = 'NETWORK STATUS';
$_MAG_DATA['get_localization']['network_status_refresh'] = 'REFRESH';
$_MAG_DATA['get_localization']['test_speed'] = 'Speed test';
$_MAG_DATA['get_localization']['speedtest_testing'] = 'testing...';
$_MAG_DATA['get_localization']['speedtest_error'] = 'error';
$_MAG_DATA['get_localization']['speedtest_waiting'] = 'waiting...';
$_MAG_DATA['get_localization']['lan_up'] = 'UP';
$_MAG_DATA['get_localization']['lan_down'] = 'DOWN';
$_MAG_DATA['get_localization']['download_stopped'] = 'stopped';
$_MAG_DATA['get_localization']['download_waiting_queue'] = 'waiting queue';
$_MAG_DATA['get_localization']['download_running'] = 'running';
$_MAG_DATA['get_localization']['download_completed'] = 'completed';
$_MAG_DATA['get_localization']['download_temporary_error'] = 'temporary error';
$_MAG_DATA['get_localization']['download_permanent_error'] = 'permanent error';
$_MAG_DATA['get_localization']['auth_title'] = 'Authentication';
$_MAG_DATA['get_localization']['auth_login'] = 'Login';
$_MAG_DATA['get_localization']['auth_password'] = 'Password';
$_MAG_DATA['get_localization']['auth_error'] = 'Error';
$_MAG_DATA['get_localization']['play_or_download'] = 'Play this url or start download?';
$_MAG_DATA['get_localization']['player_play'] = 'Play';
$_MAG_DATA['get_localization']['player_download'] = 'Download';
$_MAG_DATA['get_localization']['play_all'] = 'Play all';
$_MAG_DATA['get_localization']['on'] = 'on';
$_MAG_DATA['get_localization']['off'] = 'off';
$_MAG_DATA['get_localization']['smb_auth'] = 'Network authentication';
$_MAG_DATA['get_localization']['smb_username'] = 'Login';
$_MAG_DATA['get_localization']['smb_password'] = 'Password';
$_MAG_DATA['get_localization']['exit_title'] = 'Do you really want to exit?';
$_MAG_DATA['get_localization']['identical_download_exist'] = 'There is an active downloads from this server';
$_MAG_DATA['get_localization']['alert_form_title'] = 'Alert';
$_MAG_DATA['get_localization']['confirm_form_title'] = 'Confirm';
$_MAG_DATA['get_localization']['notice_form_title'] = 'Notice';
$_MAG_DATA['get_localization']['select_form_title'] = 'Select';
$_MAG_DATA['get_localization']['media_favorites'] = 'Favorites';
$_MAG_DATA['get_localization']['stb_type_not_supported'] = 'Your STB is not supported';
$_MAG_DATA['get_localization']['Phone'] = 'Phone';
$_MAG_DATA['get_localization']['Tariff plan'] = 'Tariff plan';
$_MAG_DATA['get_localization']['User'] = 'User';
$_MAG_DATA['get_localization']['SERVICES MANAGEMENT'] = 'SERVICES MANAGEMENT';
$_MAG_DATA['get_localization']['SUBSCRIBE'] = 'SUBSCRIBE';
$_MAG_DATA['get_localization']['UNSUBSCRIBE'] = 'UNSUBSCRIBE';
$_MAG_DATA['get_localization']['package_info_title'] = 'PACKAGE INFO';
$_MAG_DATA['get_localization']['package_type'] = 'Type';
$_MAG_DATA['get_localization']['package_content'] = 'Content';
$_MAG_DATA['get_localization']['package_description'] = 'Description';
$_MAG_DATA['get_localization']['confirm_service_subscribe_text'] = 'Are you really want to subscribe to this service?';
$_MAG_DATA['get_localization']['confirm_service_unsubscribe_text'] = 'Are you really want to unsubscribe from this service?';
$_MAG_DATA['get_localization']['confirm_service_price_text'] = 'The service costs {0}';
$_MAG_DATA['get_localization']['service_subscribe_success'] = 'You have successfully subscribed to the service.';
$_MAG_DATA['get_localization']['service_unsubscribe_success'] = 'You have successfully unsubscribed from the service.';
$_MAG_DATA['get_localization']['service_subscribe_success_reboot'] = 'You have successfully subscribed to the service.  STB will be rebooted.';
$_MAG_DATA['get_localization']['service_unsubscribe_success_reboot'] = 'You have successfully unsubscribed from the service. STB will be rebooted.';
$_MAG_DATA['get_localization']['service_subscribe_fail'] = 'An error in the management of subscriptions.';
$_MAG_DATA['get_localization']['service_subscribe_server_error'] = 'Server error. Try again later.';
$_MAG_DATA['get_localization']['package_price_measurement'] = 'UAH';
$_MAG_DATA['get_localization']['rent_movie_text'] = 'Do you really want to rent this movie?';
$_MAG_DATA['get_localization']['rent_movie_price_text'] = 'The movie costs {0}';
$_MAG_DATA['get_localization']['rent_duration_text'] = 'Rent duration: {0}h';
$_MAG_DATA['get_localization']['Account number'] = 'Account number';
$_MAG_DATA['get_localization']['End date'] = 'End date';
$_MAG_DATA['get_localization']['3D mode'] = '3D mode';
$_MAG_DATA['get_localization']['mode {0}'] = 'mode {0}';
$_MAG_DATA['get_localization']['no epg'] = 'no epg';
$_MAG_DATA['get_localization']['wrong epg'] = 'wrong epg';
$_MAG_DATA['get_localization']['iso_title'] = 'Title';
$_MAG_DATA['get_localization']['error_channel_nothing_to_play'] = 'Channel not available';
$_MAG_DATA['get_localization']['error_channel_limit'] = 'Channel temporary unavailable';
$_MAG_DATA['get_localization']['error_channel_not_available_for_zone'] = 'Channel not available for this region';
$_MAG_DATA['get_localization']['error_channel_link_fault'] = 'Channel not available. Server error.';
$_MAG_DATA['get_localization']['error_channel_access_denied'] = 'Access denied';
$_MAG_DATA['get_localization']['blocking_account_info'] = 'Account info';
$_MAG_DATA['get_localization']['blocking_account_payment'] = 'Payment';
$_MAG_DATA['get_localization']['blocking_account_reboot'] = 'Reload portal';
$_MAG_DATA['get_localization']['archive_continue_playing_text'] = 'Continue playing?';
$_MAG_DATA['get_localization']['archive_yes'] = 'YES';
$_MAG_DATA['get_localization']['archive_no'] = 'NO';
$_MAG_DATA['get_localization']['time_shift_exit_confirm_text'] = 'Do you want to quit the Time Shift mode?';
$_MAG_DATA['get_localization']['mbrowser_sort_by_name'] = 'by name';
$_MAG_DATA['get_localization']['mbrowser_sort_by_date'] = 'by date';
$_MAG_DATA['get_localization']['Connection problem'] = 'Connection problem';
$_MAG_DATA['get_localization']['Authentication problem'] = 'Authentication problem';
$_MAG_DATA['get_localization']['Account balance'] = 'Account balance';
$_MAG_DATA['get_localization']['remote_pvr_confirm_text'] = 'Start recording on the server?';
$_MAG_DATA['get_localization']['remote_deferred_pvr_confirm_text'] = 'Do you really want to schedule a recording on the server?';
$_MAG_DATA['get_localization']['pvr_target_select_text'] = 'Select where to save the record';
$_MAG_DATA['get_localization']['usb_target_btn'] = 'USB Storage';
$_MAG_DATA['get_localization']['server_target_btn'] = 'Server';
$_MAG_DATA['get_localization']['save_path'] = 'Path';
$_MAG_DATA['get_localization']['file_name'] = 'Filename';
$_MAG_DATA['get_localization']['usb_device'] = 'USB Device';
$_MAG_DATA['get_localization']['rec_stop_msg'] = 'Stopped recording â€” {0} on channel {1}';
$_MAG_DATA['get_localization']['rec_file_missing'] = 'The recorded file is missing';
$_MAG_DATA['get_localization']['rec_not_ended'] = 'Recording is not finished yet';
$_MAG_DATA['get_localization']['rec_channel_has_scheduled_recording'] = 'The channel already has a scheduled recording';
$_MAG_DATA['get_localization']['pvr_error_wrong_param'] = 'PVR Error: Wrong parameter';
$_MAG_DATA['get_localization']['pvr_error_memory'] = 'PVR Error: Not enough memory to complete the operation';
$_MAG_DATA['get_localization']['pvr_error_duration'] = 'PVR Error: Incorrect recording range';
$_MAG_DATA['get_localization']['pvr_error_not_found'] = 'PVR Error: Task not found';
$_MAG_DATA['get_localization']['pvr_error_wrong_filename'] = 'PVR Error: Wrong filename';
$_MAG_DATA['get_localization']['pvr_error_record_exist'] = 'PVR Error: Record file already exists';
$_MAG_DATA['get_localization']['pvr_error_url_open_error'] = 'PVR Error: Error opening channel URL';
$_MAG_DATA['get_localization']['pvr_error_file_open_error'] = 'PVR Error: Error opening file';
$_MAG_DATA['get_localization']['pvr_error_rec_limit'] = 'PVR Error: Exceeded the maximum number simultaneous recordings';
$_MAG_DATA['get_localization']['pvr_error_end_of_stream'] = 'PVR Error: End of stream';
$_MAG_DATA['get_localization']['pvr_error_file_write_error'] = 'PVR Error: Error writing to file';
$_MAG_DATA['get_localization']['pvr_start_time'] = 'Start time';
$_MAG_DATA['get_localization']['pvr_end_time'] = 'End time';
$_MAG_DATA['get_localization']['pvr_duration'] = 'Duration';
$_MAG_DATA['get_localization']['rec_options_form_title'] = 'Recording';
$_MAG_DATA['get_localization']['local_pvr_interrupted'] = 'Recording on USB device interrupted';
$_MAG_DATA['get_localization']['parent_password_error'] = 'Wrong';
$_MAG_DATA['get_localization']['parent_password_title'] = 'Parent control';
$_MAG_DATA['get_localization']['password_label'] = 'Password';
$_MAG_DATA['get_localization']['encoding_label'] = 'Encoding';
$_MAG_DATA['get_localization']['network_folder'] = 'Network folder';
$_MAG_DATA['get_localization']['server_ip'] = 'IP address';
$_MAG_DATA['get_localization']['server_path'] = 'Path';
$_MAG_DATA['get_localization']['local_folder'] = 'Local folder';
$_MAG_DATA['get_localization']['server_type'] = 'Type';
$_MAG_DATA['get_localization']['server_login'] = 'Login';
$_MAG_DATA['get_localization']['server_password'] = 'Password';
$_MAG_DATA['get_localization']['add_folder'] = 'ADD';
$_MAG_DATA['get_localization']['server_ip_placeholder'] = 'Server address';
$_MAG_DATA['get_localization']['server_path_placeholder'] = 'Path to the folder';
$_MAG_DATA['get_localization']['local_folder_placeholder'] = 'Folder name in favorites';
$_MAG_DATA['get_localization']['error'] = 'error';
$_MAG_DATA['get_localization']['mount_failed'] = 'Mount failed';
$_MAG_DATA['get_localization']['ad_skip'] = 'SKIP';
$_MAG_DATA['get_localization']['commercial'] = 'COMMERCIAL';
$_MAG_DATA['get_localization']['videoClockTitle'] = 'Clock';
$_MAG_DATA['get_localization']['videoClock_off'] = 'Hidden';
$_MAG_DATA['get_localization']['videoClock_upRight'] = 'Top Right';
$_MAG_DATA['get_localization']['videoClock_upLeft'] = 'Top Left';
$_MAG_DATA['get_localization']['videoClock_downRight'] = 'Bottom Right';
$_MAG_DATA['get_localization']['videoClock_downLeft'] = 'Bottom Left';
$_MAG_DATA['get_localization']['settings_unavailable'] = 'Settings section is currently unavailable';
$_MAG_DATA['get_localization']['no_dvb_channels_title'] = 'No channels available';
$_MAG_DATA['get_localization']['go_to_dvb_settings'] = 'You can configure DVB channels in the settings menu';
$_MAG_DATA['get_localization']['apps_title'] = 'Applications';
$_MAG_DATA['get_localization']['coming_soon_video'] = 'Video will be available soon';
$_MAG_DATA['get_profile']['name'] = '';
$_MAG_DATA['get_profile']['sname'] = '';
$_MAG_DATA['get_profile']['pass'] = '';
$_MAG_DATA['get_profile']['additional_services_on'] = '';
$_MAG_DATA['get_profile']['operator_id'] = '0';
$_MAG_DATA['get_profile']['storage_name'] = '';
$_MAG_DATA['get_profile']['phone'] = '';
$_MAG_DATA['get_profile']['tv_quality'] = 'high';
$_MAG_DATA['get_profile']['fname'] = 'nets';
$_MAG_DATA['get_profile']['login'] = '';
$_MAG_DATA['get_profile']['password'] = '';
$_MAG_DATA['get_profile']['num_banks'] = '0';
$_MAG_DATA['get_profile']['tariff_plan_id'] = '1';
$_MAG_DATA['get_profile']['comment'] = '';
$_MAG_DATA['get_profile']['now_playing_link_id'] = '0';
$_MAG_DATA['get_profile']['now_playing_streamer_id'] = '0';
$_MAG_DATA['get_profile']['just_started'] = '1';
$_MAG_DATA['get_profile']['verified'] = '0';
$_MAG_DATA['get_profile']['pri_audio_lang'] = '';
$_MAG_DATA['get_profile']['sec_audio_lang'] = '';
$_MAG_DATA['get_profile']['pri_subtitle_lang'] = '';
$_MAG_DATA['get_profile']['sec_subtitle_lang'] = '';
$_MAG_DATA['get_profile']['hw_version'] = 'undefined';
$_MAG_DATA['get_profile']['storages'] = '';
$_MAG_DATA['get_profile']['last_itv_id'] = '1';
$_MAG_DATA['get_profile']['updated'] = '';
$_MAG_DATA['get_profile']['web_proxy_host'] = '';
$_MAG_DATA['get_profile']['web_proxy_port'] = '';
$_MAG_DATA['get_profile']['web_proxy_user'] = '';
$_MAG_DATA['get_profile']['web_proxy_pass'] = '';
$_MAG_DATA['get_profile']['web_proxy_exclude_list'] = '';
$_MAG_DATA['get_profile']['demo_video_url'] = '';
$_MAG_DATA['get_profile']['tv_quality_filter'] = '';
$_MAG_DATA['get_profile']['use_embedded_settings'] = '';
$_MAG_DATA['get_profile']['is_moderator'] = '';
$_MAG_DATA['get_profile']['timeslot_ratio'] = '0.94530244530245';
$_MAG_DATA['get_profile']['timeslot'] = '113.43629343629';
$_MAG_DATA['get_profile']['kinopoisk_rating'] = '1';
$_MAG_DATA['get_profile']['enable_tariff_plans'] = '1';
$_MAG_DATA['get_profile']['enable_buffering_indication'] = '1';
$_MAG_DATA['get_profile']['allowed_stb_types_for_local_recording'] = ['mag245', 'mag254', 'mag250', 'mag255', 'mag256', 'mag270', 'mag275', 'aurahd'];
$_MAG_DATA['get_profile']['strict_stb_type_check'] = '';
$_MAG_DATA['get_profile']['cas_params'] = '';
$_MAG_DATA['get_profile']['enable_hdmi_events_handler'] = '1';
$_MAG_DATA['get_profile']['cas_additional_params'] = '';
$_MAG_DATA['get_profile']['cas_ini_file'] = '';
$_MAG_DATA['get_profile']['logarithm_volume_control'] = '1';
$_MAG_DATA['get_profile']['allow_subscription_from_stb'] = '1';
$_MAG_DATA['get_profile']['deny_720p_gmode_720_on_mag200'] = '1';
$_MAG_DATA['get_profile']['enable_arrow_keys_setpos'] = '1';
$_MAG_DATA['get_profile']['show_purchased_filter'] = '';
$_MAG_DATA['get_profile']['enable_connection_problem_indication'] = '1';
$_MAG_DATA['get_profile']['invert_channel_switch_direction'] = '';
$_MAG_DATA['get_profile']['enable_stream_error_logging'] = '';
$_MAG_DATA['get_profile']['always_enabled_subtitles'] = '';
$_MAG_DATA['get_profile']['enable_service_button'] = '';
$_MAG_DATA['get_profile']['show_tv_channel_logo'] = '1';
$_MAG_DATA['get_profile']['tv_archive_continued'] = '';
$_MAG_DATA['get_profile']['show_tv_only_hd_filter_option'] = '';
$_MAG_DATA['get_profile']['tv_playback_retry_limit'] = '3';
$_MAG_DATA['get_profile']['fading_tv_retry_timeout'] = '1';
$_MAG_DATA['get_profile']['epg_update_time_range'] = '3108';
$_MAG_DATA['get_profile']['store_auth_data_on_stb'] = '';
$_MAG_DATA['get_profile']['account_page_by_password'] = '';
$_MAG_DATA['get_profile']['tester'] = '';
$_MAG_DATA['get_profile']['show_channel_logo_in_preview'] = '';
$_MAG_DATA['get_profile']['enable_stream_losses_logging'] = '';
$_MAG_DATA['get_profile']['external_payment_page_url'] = '';
$_MAG_DATA['get_profile']['max_local_recordings'] = '10';
$_MAG_DATA['gmode_720'][0] = 'template/default/i_720/horoscope_menu_button_1_1_b.png';
$_MAG_DATA['gmode_720'][1] = 'template/default/i_720/footer_menu_act.png';
$_MAG_DATA['gmode_720'][2] = 'template/default/i_720/tv_table.png';
$_MAG_DATA['gmode_720'][3] = 'template/default/i_720/dots.png';
$_MAG_DATA['gmode_720'][4] = 'template/default/i_720/mb_table05.png';
$_MAG_DATA['gmode_720'][5] = 'template/default/i_720/1.png';
$_MAG_DATA['gmode_720'][6] = 'template/default/i_720/0.png';
$_MAG_DATA['gmode_720'][7] = 'template/default/i_720/mb_table07.png';
$_MAG_DATA['gmode_720'][8] = 'template/default/i_720/horoscope_menu_button_1_5_a.png';
$_MAG_DATA['gmode_720'][9] = 'template/default/i_720/mm_ico_youtube.png';
$_MAG_DATA['gmode_720'][10] = 'template/default/i_720/25alfa_20.png';
$_MAG_DATA['gmode_720'][11] = 'template/default/i_720/6.png';
$_MAG_DATA['gmode_720'][12] = 'template/default/i_720/osd_bg.png';
$_MAG_DATA['gmode_720'][13] = 'template/default/i_720/_6_lightning.png';
$_MAG_DATA['gmode_720'][14] = 'template/default/i_720/ico_issue.png';
$_MAG_DATA['gmode_720'][15] = 'template/default/i_720/osd_btn.png';
$_MAG_DATA['gmode_720'][16] = 'template/default/i_720/horoscope_menu_button_1_1_a.png';
$_MAG_DATA['gmode_720'][17] = 'template/default/i_720/mm_ico_info.png';
$_MAG_DATA['gmode_720'][18] = 'template/default/i_720/horoscope_menu_button_1_7_b.png';
$_MAG_DATA['gmode_720'][19] = 'template/default/i_720/horoscope_menu_button_1_10_b.png';
$_MAG_DATA['gmode_720'][20] = 'template/default/i_720/mm_vert_cell.png';
$_MAG_DATA['gmode_720'][21] = 'template/default/i_720/mb_scroll.png';
$_MAG_DATA['gmode_720'][22] = 'template/default/i_720/mb_table06.png';
$_MAG_DATA['gmode_720'][23] = 'template/default/i_720/skip.png';
$_MAG_DATA['gmode_720'][24] = 'template/default/i_720/mb_pass_input.png';
$_MAG_DATA['gmode_720'][25] = 'template/default/i_720/mm_ico_account.png';
$_MAG_DATA['gmode_720'][26] = 'template/default/i_720/mm_ico_tv.png';
$_MAG_DATA['gmode_720'][27] = 'template/default/i_720/mb_table_act04.png';
$_MAG_DATA['gmode_720'][28] = 'template/default/i_720/horoscope_menu_button_1_10_a.png';
$_MAG_DATA['gmode_720'][29] = 'template/default/i_720/mb_table04.png';
$_MAG_DATA['gmode_720'][30] = 'template/default/i_720/_3_pasmurno.png';
$_MAG_DATA['gmode_720'][31] = 'template/default/i_720/deg.png';
$_MAG_DATA['gmode_720'][32] = 'template/default/i_720/horoscope_menu_button_1_2_a.png';
$_MAG_DATA['gmode_720'][33] = 'template/default/i_720/v_menu_1b.png';
$_MAG_DATA['gmode_720'][34] = 'template/default/i_720/epg_red_mark.png';
$_MAG_DATA['gmode_720'][35] = 'template/default/i_720/mb_prev_bg.png';
$_MAG_DATA['gmode_720'][36] = 'template/default/i_720/aspect_bg.png';
$_MAG_DATA['gmode_720'][37] = 'template/default/i_720/modal_bg.png';
$_MAG_DATA['gmode_720'][38] = 'template/default/i_720/osd_line_pos.png';
$_MAG_DATA['gmode_720'][39] = 'template/default/i_720/black85.png';
$_MAG_DATA['gmode_720'][40] = 'template/default/i_720/input.png';
$_MAG_DATA['gmode_720'][41] = 'template/default/i_720/input_episode_bg.png';
$_MAG_DATA['gmode_720'][42] = 'template/default/i_720/mb_table_act05.png';
$_MAG_DATA['gmode_720'][43] = 'template/default/i_720/_0_moon.png';
$_MAG_DATA['gmode_720'][44] = 'template/default/i_720/_0_sun.png';
$_MAG_DATA['gmode_720'][45] = 'template/default/i_720/ico_alert.png';
$_MAG_DATA['gmode_720'][46] = 'template/default/i_720/ears.png';
$_MAG_DATA['gmode_720'][47] = 'template/default/i_720/5.png';
$_MAG_DATA['gmode_720'][48] = 'template/default/i_720/1x1.gif';
$_MAG_DATA['gmode_720'][49] = 'template/default/i_720/footer_sidepanel_arr.png';
$_MAG_DATA['gmode_720'][50] = 'template/default/i_720/horoscope_menu_button_1_9_b.png';
$_MAG_DATA['gmode_720'][51] = 'template/default/i_720/mm_ico_internet.png';
$_MAG_DATA['gmode_720'][52] = 'template/default/i_720/mm_hor_left.png';
$_MAG_DATA['gmode_720'][53] = 'template/default/i_720/v_menu_5.png';
$_MAG_DATA['gmode_720'][54] = 'template/default/i_720/ears_arrow_l.png';
$_MAG_DATA['gmode_720'][55] = 'template/default/i_720/footer_sidepanel_line.png';
$_MAG_DATA['gmode_720'][56] = 'template/default/i_720/horoscope_menu_button_1_8_a.png';
$_MAG_DATA['gmode_720'][57] = 'template/default/i_720/_2_cloudy.png';
$_MAG_DATA['gmode_720'][58] = 'template/default/i_720/input_episode.png';
$_MAG_DATA['gmode_720'][59] = 'template/default/i_720/ico_error26.png';
$_MAG_DATA['gmode_720'][60] = 'template/default/i_720/osd_rec.png';
$_MAG_DATA['gmode_720'][61] = 'template/default/i_720/footer_sidepanel_l.png';
$_MAG_DATA['gmode_720'][62] = 'template/default/i_720/mb_quality.png';
$_MAG_DATA['gmode_720'][63] = 'template/default/i_720/footer_search.png';
$_MAG_DATA['gmode_720'][64] = 'template/default/i_720/tv_table_arrows.png';
$_MAG_DATA['gmode_720'][65] = 'template/default/i_720/ears_arrow_r.png';
$_MAG_DATA['gmode_720'][66] = 'template/default/i_720/footer_bg.png';
$_MAG_DATA['gmode_720'][67] = 'template/default/i_720/volume_off.png';
$_MAG_DATA['gmode_720'][68] = 'template/default/i_720/_255_NA.png';
$_MAG_DATA['gmode_720'][69] = 'template/default/i_720/7.png';
$_MAG_DATA['gmode_720'][70] = 'template/default/i_720/mb_icon_rec.png';
$_MAG_DATA['gmode_720'][71] = 'template/default/i_720/mb_icon_scrambled.png';
$_MAG_DATA['gmode_720'][72] = 'template/default/i_720/arr_right.png';
$_MAG_DATA['gmode_720'][73] = 'template/default/i_720/footer_sidepanel_act.png';
$_MAG_DATA['gmode_720'][74] = 'template/default/i_720/mb_table01.png';
$_MAG_DATA['gmode_720'][75] = 'template/default/i_720/tv_table_separator.png';
$_MAG_DATA['gmode_720'][76] = 'template/default/i_720/mm_ico_android.png';
$_MAG_DATA['gmode_720'][77] = 'template/default/i_720/mm_ico_ivi.png';
$_MAG_DATA['gmode_720'][78] = 'template/default/i_720/mm_hor_bg1.png';
$_MAG_DATA['gmode_720'][79] = 'template/default/i_720/mm_ico_usb.png';
$_MAG_DATA['gmode_720'][80] = 'template/default/i_720/mm_ico_pomogator.png';
$_MAG_DATA['gmode_720'][81] = 'template/default/i_720/mm_ico_zoomby.png';
$_MAG_DATA['gmode_720'][82] = 'template/default/i_720/horoscope_menu_button_1_3_b.png';
$_MAG_DATA['gmode_720'][83] = 'template/default/i_720/_1_sun_cl.png';
$_MAG_DATA['gmode_720'][84] = 'template/default/i_720/mm_ico_tvzavr.png';
$_MAG_DATA['gmode_720'][85] = 'template/default/i_720/2.png';
$_MAG_DATA['gmode_720'][86] = 'template/default/i_720/epg_orange_mark.png';
$_MAG_DATA['gmode_720'][87] = 'template/default/i_720/volume_bg.png';
$_MAG_DATA['gmode_720'][88] = 'template/default/i_720/horoscope_menu_button_1_9_a.png';
$_MAG_DATA['gmode_720'][89] = 'template/default/i_720/v_menu_3.png';
$_MAG_DATA['gmode_720'][90] = 'template/default/i_720/horoscope_menu_button_1_6_b.png';
$_MAG_DATA['gmode_720'][91] = 'template/default/i_720/input_act.png';
$_MAG_DATA['gmode_720'][92] = 'template/default/i_720/_7_hail.png';
$_MAG_DATA['gmode_720'][93] = 'template/default/i_720/mm_ico_setting.png';
$_MAG_DATA['gmode_720'][94] = 'template/default/i_720/tv_table_focus.png';
$_MAG_DATA['gmode_720'][95] = 'template/default/i_720/mb_context_bg.png';
$_MAG_DATA['gmode_720'][96] = 'template/default/i_720/mb_filminfo_trans.png';
$_MAG_DATA['gmode_720'][97] = 'template/default/i_720/horoscope_menu_button_1_12_b.png';
$_MAG_DATA['gmode_720'][98] = 'template/default/i_720/mb_table_act02.png';
$_MAG_DATA['gmode_720'][99] = 'template/default/i_720/mm_hor_right.png';
$_MAG_DATA['gmode_720'][100] = 'template/default/i_720/epg_green_mark.png';
$_MAG_DATA['gmode_720'][101] = 'template/default/i_720/v_menu_2b.png';
$_MAG_DATA['gmode_720'][102] = 'template/default/i_720/_1_moon_cl.png';
$_MAG_DATA['gmode_720'][103] = 'template/default/i_720/horoscope_menu_button_1_11_a.png';
$_MAG_DATA['gmode_720'][104] = 'template/default/i_720/footer_sidepanel.png';
$_MAG_DATA['gmode_720'][105] = 'template/default/i_720/v_menu_1a.png';
$_MAG_DATA['gmode_720'][106] = 'template/default/i_720/hr_filminfo.png';
$_MAG_DATA['gmode_720'][107] = 'template/default/i_720/horoscope_menu_button_1_5_b.png';
$_MAG_DATA['gmode_720'][108] = 'template/default/i_720/horoscope_menu_button_1_2_b.png';
$_MAG_DATA['gmode_720'][109] = 'template/default/i_720/mm_hor_bg3.png';
$_MAG_DATA['gmode_720'][110] = 'template/default/i_720/horoscope_menu_button_1_6_a.png';
$_MAG_DATA['gmode_720'][111] = 'template/default/i_720/mm_ico_ex.png';
$_MAG_DATA['gmode_720'][112] = 'template/default/i_720/item_bg.png';
$_MAG_DATA['gmode_720'][113] = 'template/default/i_720/footer_bg2.png';
$_MAG_DATA['gmode_720'][114] = 'template/default/i_720/horoscope_menu_button_1_3_a.png';
$_MAG_DATA['gmode_720'][115] = 'template/default/i_720/low_q.png';
$_MAG_DATA['gmode_720'][116] = 'template/default/i_720/8.png';
$_MAG_DATA['gmode_720'][117] = 'template/default/i_720/4.png';
$_MAG_DATA['gmode_720'][118] = 'template/default/i_720/horoscope_menu_button_1_4_b.png';
$_MAG_DATA['gmode_720'][119] = 'template/default/i_720/mm_ico_apps.png';
$_MAG_DATA['gmode_720'][120] = 'template/default/i_720/mm_ico_megogo.png';
$_MAG_DATA['gmode_720'][121] = 'template/default/i_720/footer_btn.png';
$_MAG_DATA['gmode_720'][122] = 'template/default/i_720/mb_scroll_bg.png';
$_MAG_DATA['gmode_720'][123] = 'template/default/i_720/bg.png';
$_MAG_DATA['gmode_720'][124] = 'template/default/i_720/btn2.png';
$_MAG_DATA['gmode_720'][125] = 'template/default/i_720/mb_context_borders.png';
$_MAG_DATA['gmode_720'][126] = 'template/default/i_720/horoscope_menu_button_1_11_b.png';
$_MAG_DATA['gmode_720'][127] = 'template/default/i_720/_10_heavy_snow.png';
$_MAG_DATA['gmode_720'][128] = 'template/default/i_720/mb_icons.png';
$_MAG_DATA['gmode_720'][129] = 'template/default/i_720/3.png';
$_MAG_DATA['gmode_720'][130] = 'template/default/i_720/_5_rain.png';
$_MAG_DATA['gmode_720'][131] = 'template/default/i_720/mb_table_act06.png';
$_MAG_DATA['gmode_720'][132] = 'template/default/i_720/mm_ico_dm.png';
$_MAG_DATA['gmode_720'][133] = 'template/default/i_720/volume_bar.png';
$_MAG_DATA['gmode_720'][134] = 'template/default/i_720/footer_sidepanel_r.png';
$_MAG_DATA['gmode_720'][135] = 'template/default/i_720/ico_confirm.png';
$_MAG_DATA['gmode_720'][136] = 'template/default/i_720/mb_table_act01.png';
$_MAG_DATA['gmode_720'][137] = 'template/default/i_720/footer_menu.png';
$_MAG_DATA['gmode_720'][138] = 'template/default/i_720/ico_info.png';
$_MAG_DATA['gmode_720'][139] = 'template/default/i_720/minus.png';
$_MAG_DATA['gmode_720'][140] = 'template/default/i_720/mm_ico_karaoke.png';
$_MAG_DATA['gmode_720'][141] = 'template/default/i_720/v_menu_2a.png';
$_MAG_DATA['gmode_720'][142] = 'template/default/i_720/_9_snow.png';
$_MAG_DATA['gmode_720'][143] = 'template/default/i_720/mb_table_act03.png';
$_MAG_DATA['gmode_720'][144] = 'template/default/i_720/mm_ico_video.png';
$_MAG_DATA['gmode_720'][145] = 'template/default/i_720/footer_search_act2.png';
$_MAG_DATA['gmode_720'][146] = 'template/default/i_720/input_channel.png';
$_MAG_DATA['gmode_720'][147] = 'template/default/i_720/horoscope_menu_button_1_4_a.png';
$_MAG_DATA['gmode_720'][148] = 'template/default/i_720/osd_time.png';
$_MAG_DATA['gmode_720'][149] = 'template/default/i_720/tv_prev_bg.png';
$_MAG_DATA['gmode_720'][150] = 'template/default/i_720/osd_line.png';
$_MAG_DATA['gmode_720'][151] = 'template/default/i_720/horoscope_menu_button_1_7_a.png';
$_MAG_DATA['gmode_720'][152] = 'template/default/i_720/9.png';
$_MAG_DATA['gmode_720'][153] = 'template/default/i_720/mb_table03.png';
$_MAG_DATA['gmode_720'][154] = 'template/default/i_720/pause_btn.png';
$_MAG_DATA['gmode_720'][155] = 'template/default/i_720/input_channel_bg.png';
$_MAG_DATA['gmode_720'][156] = 'template/default/i_720/mb_pass_bg.png';
$_MAG_DATA['gmode_720'][157] = 'template/default/i_720/mm_hor_bg2.png';
$_MAG_DATA['gmode_720'][158] = 'template/default/i_720/loading.png';
$_MAG_DATA['gmode_720'][159] = 'template/default/i_720/_4_short_rain.png';
$_MAG_DATA['gmode_720'][160] = 'template/default/i_720/v_menu_4.png';
$_MAG_DATA['gmode_720'][161] = 'template/default/i_720/arr_left.png';
$_MAG_DATA['gmode_720'][162] = 'template/default/i_720/horoscope_menu_button_1_8_b.png';
$_MAG_DATA['gmode_720'][163] = 'template/default/i_720/mb_table02.png';
$_MAG_DATA['gmode_720'][164] = 'template/default/i_720/bg2.png';
$_MAG_DATA['gmode_720'][165] = 'template/default/i_720/mm_ico_radio.png';
$_MAG_DATA['gmode_720'][166] = 'template/default/i_720/mm_ico_vidimax.png';
$_MAG_DATA['gmode_720'][167] = 'template/default/i_720/mb_player.png';
$_MAG_DATA['gmode_720'][168] = 'template/default/i_720/_8_rain_swon.png';
$_MAG_DATA['gmode_720'][169] = 'template/default/i_720/loading_bg.gif';
$_MAG_DATA['gmode_720'][170] = 'template/default/i_720/plus.png';
$_MAG_DATA['gmode_720'][171] = 'template/default/i_720/footer_search_act.png';
$_MAG_DATA['gmode_720'][172] = 'template/default/i_720/vol_1.png';
$_MAG_DATA['gmode_720'][173] = 'template/default/i_720/mm_ico_oll.png';
$_MAG_DATA['gmode_720'][174] = 'template/default/i_720/horoscope_menu_button_1_12_a.png';
$_MAG_DATA['gmode_480'][0] = 'template/default/i_480/horoscope_menu_button_1_1_b.png';
$_MAG_DATA['gmode_480'][1] = 'template/default/i_480/footer_menu_act.png';
$_MAG_DATA['gmode_480'][2] = 'template/default/i_480/tv_table.png';
$_MAG_DATA['gmode_480'][3] = 'template/default/i_480/dots.png';
$_MAG_DATA['gmode_480'][4] = 'template/default/i_480/ears2.png';
$_MAG_DATA['gmode_480'][5] = 'template/default/i_480/1.png';
$_MAG_DATA['gmode_480'][6] = 'template/default/i_480/0.png';
$_MAG_DATA['gmode_480'][7] = 'template/default/i_480/w_snow.png';
$_MAG_DATA['gmode_480'][8] = 'template/default/i_480/horoscope_menu_button_1_5_a.png';
$_MAG_DATA['gmode_480'][9] = 'template/default/i_480/mm_ico_youtube.png';
$_MAG_DATA['gmode_480'][10] = 'template/default/i_480/25alfa_20.png';
$_MAG_DATA['gmode_480'][11] = 'template/default/i_480/6.png';
$_MAG_DATA['gmode_480'][12] = 'template/default/i_480/osd_bg.png';
$_MAG_DATA['gmode_480'][13] = 'template/default/i_480/_6_lightning.png';
$_MAG_DATA['gmode_480'][14] = 'template/default/i_480/ico_issue.png';
$_MAG_DATA['gmode_480'][15] = 'template/default/i_480/osd_btn.png';
$_MAG_DATA['gmode_480'][16] = 'template/default/i_480/horoscope_menu_button_1_1_a.png';
$_MAG_DATA['gmode_480'][17] = 'template/default/i_480/mm_ico_info.png';
$_MAG_DATA['gmode_480'][18] = 'template/default/i_480/horoscope_menu_button_1_7_b.png';
$_MAG_DATA['gmode_480'][19] = 'template/default/i_480/horoscope_menu_button_1_10_b.png';
$_MAG_DATA['gmode_480'][20] = 'template/default/i_480/mm_vert_cell.png';
$_MAG_DATA['gmode_480'][21] = 'template/default/i_480/mb_scroll.png';
$_MAG_DATA['gmode_480'][22] = 'template/default/i_480/skip.png';
$_MAG_DATA['gmode_480'][23] = 'template/default/i_480/mb_pass_input.png';
$_MAG_DATA['gmode_480'][24] = 'template/default/i_480/mm_ico_account.png';
$_MAG_DATA['gmode_480'][25] = 'template/default/i_480/mm_ico_tv.png';
$_MAG_DATA['gmode_480'][26] = 'template/default/i_480/horoscope_menu_button_1_10_a.png';
$_MAG_DATA['gmode_480'][27] = 'template/default/i_480/w_thunderstorm.png';
$_MAG_DATA['gmode_480'][28] = 'template/default/i_480/w_moon.png';
$_MAG_DATA['gmode_480'][29] = 'template/default/i_480/_3_pasmurno.png';
$_MAG_DATA['gmode_480'][30] = 'template/default/i_480/deg.png';
$_MAG_DATA['gmode_480'][31] = 'template/default/i_480/horoscope_menu_button_1_2_a.png';
$_MAG_DATA['gmode_480'][32] = 'template/default/i_480/v_menu_1b.png';
$_MAG_DATA['gmode_480'][33] = 'template/default/i_480/epg_red_mark.png';
$_MAG_DATA['gmode_480'][34] = 'template/default/i_480/weather.png';
$_MAG_DATA['gmode_480'][35] = 'template/default/i_480/mb_prev_bg.png';
$_MAG_DATA['gmode_480'][36] = 'template/default/i_480/aspect_bg.png';
$_MAG_DATA['gmode_480'][37] = 'template/default/i_480/modal_bg.png';
$_MAG_DATA['gmode_480'][38] = 'template/default/i_480/osd_line_pos.png';
$_MAG_DATA['gmode_480'][39] = 'template/default/i_480/mm_vert_border.png';
$_MAG_DATA['gmode_480'][40] = 'template/default/i_480/black85.png';
$_MAG_DATA['gmode_480'][41] = 'template/default/i_480/input.png';
$_MAG_DATA['gmode_480'][42] = 'template/default/i_480/input_episode_bg.png';
$_MAG_DATA['gmode_480'][43] = 'template/default/i_480/w_cloud_big.png';
$_MAG_DATA['gmode_480'][44] = 'template/default/i_480/_0_moon.png';
$_MAG_DATA['gmode_480'][45] = 'template/default/i_480/_0_sun.png';
$_MAG_DATA['gmode_480'][46] = 'template/default/i_480/ico_alert.png';
$_MAG_DATA['gmode_480'][47] = 'template/default/i_480/ears.png';
$_MAG_DATA['gmode_480'][48] = 'template/default/i_480/5.png';
$_MAG_DATA['gmode_480'][49] = 'template/default/i_480/1x1.gif';
$_MAG_DATA['gmode_480'][50] = 'template/default/i_480/footer_sidepanel_arr.png';
$_MAG_DATA['gmode_480'][51] = 'template/default/i_480/horoscope_menu_button_1_9_b.png';
$_MAG_DATA['gmode_480'][52] = 'template/default/i_480/menu_item_img_1.png';
$_MAG_DATA['gmode_480'][53] = 'template/default/i_480/w_empty.png';
$_MAG_DATA['gmode_480'][54] = 'template/default/i_480/mm_ico_internet.png';
$_MAG_DATA['gmode_480'][55] = 'template/default/i_480/mm_hor_left.png';
$_MAG_DATA['gmode_480'][56] = 'template/default/i_480/v_menu_5.png';
$_MAG_DATA['gmode_480'][57] = 'template/default/i_480/ears_arrow_l.png';
$_MAG_DATA['gmode_480'][58] = 'template/default/i_480/footer_sidepanel_line.png';
$_MAG_DATA['gmode_480'][59] = 'template/default/i_480/horoscope_menu_button_1_8_a.png';
$_MAG_DATA['gmode_480'][60] = 'template/default/i_480/_2_cloudy.png';
$_MAG_DATA['gmode_480'][61] = 'template/default/i_480/input_episode.png';
$_MAG_DATA['gmode_480'][62] = 'template/default/i_480/ico_error26.png';
$_MAG_DATA['gmode_480'][63] = 'template/default/i_480/mb_table.png';
$_MAG_DATA['gmode_480'][64] = 'template/default/i_480/osd_rec.png';
$_MAG_DATA['gmode_480'][65] = 'template/default/i_480/footer_sidepanel_l.png';
$_MAG_DATA['gmode_480'][66] = 'template/default/i_480/mb_quality.png';
$_MAG_DATA['gmode_480'][67] = 'template/default/i_480/footer_search.png';
$_MAG_DATA['gmode_480'][68] = 'template/default/i_480/tv_table_arrows.png';
$_MAG_DATA['gmode_480'][69] = 'template/default/i_480/ears_arrow_r.png';
$_MAG_DATA['gmode_480'][70] = 'template/default/i_480/footer_bg.png';
$_MAG_DATA['gmode_480'][71] = 'template/default/i_480/w_cloud_black.png';
$_MAG_DATA['gmode_480'][72] = 'template/default/i_480/volume_off.png';
$_MAG_DATA['gmode_480'][73] = 'template/default/i_480/_255_NA.png';
$_MAG_DATA['gmode_480'][74] = 'template/default/i_480/7.png';
$_MAG_DATA['gmode_480'][75] = 'template/default/i_480/mb_icon_rec.png';
$_MAG_DATA['gmode_480'][76] = 'template/default/i_480/mb_icon_scrambled.png';
$_MAG_DATA['gmode_480'][77] = 'template/default/i_480/arr_right.png';
$_MAG_DATA['gmode_480'][78] = 'template/default/i_480/footer_sidepanel_act.png';
$_MAG_DATA['gmode_480'][79] = 'template/default/i_480/w_rain_strong.png';
$_MAG_DATA['gmode_480'][80] = 'template/default/i_480/tv_table_separator.png';
$_MAG_DATA['gmode_480'][81] = 'template/default/i_480/mm_ico_ivi.png';
$_MAG_DATA['gmode_480'][82] = 'template/default/i_480/mm_hor_bg1.png';
$_MAG_DATA['gmode_480'][83] = 'template/default/i_480/mm_ico_usb.png';
$_MAG_DATA['gmode_480'][84] = 'template/default/i_480/vol_2.png';
$_MAG_DATA['gmode_480'][85] = 'template/default/i_480/mm_ico_pomogator.png';
$_MAG_DATA['gmode_480'][86] = 'template/default/i_480/mm_ico_zoomby.png';
$_MAG_DATA['gmode_480'][87] = 'template/default/i_480/horoscope_menu_button_1_3_b.png';
$_MAG_DATA['gmode_480'][88] = 'template/default/i_480/_1_sun_cl.png';
$_MAG_DATA['gmode_480'][89] = 'template/default/i_480/mm_ico_tvzavr.png';
$_MAG_DATA['gmode_480'][90] = 'template/default/i_480/2.png';
$_MAG_DATA['gmode_480'][91] = 'template/default/i_480/epg_orange_mark.png';
$_MAG_DATA['gmode_480'][92] = 'template/default/i_480/volume_bg.png';
$_MAG_DATA['gmode_480'][93] = 'template/default/i_480/horoscope_menu_button_1_9_a.png';
$_MAG_DATA['gmode_480'][94] = 'template/default/i_480/v_menu_3.png';
$_MAG_DATA['gmode_480'][95] = 'template/default/i_480/horoscope_menu_button_1_6_b.png';
$_MAG_DATA['gmode_480'][96] = 'template/default/i_480/input_act.png';
$_MAG_DATA['gmode_480'][97] = 'template/default/i_480/mb_context_btn.png';
$_MAG_DATA['gmode_480'][98] = 'template/default/i_480/_7_hail.png';
$_MAG_DATA['gmode_480'][99] = 'template/default/i_480/mm_ico_setting.png';
$_MAG_DATA['gmode_480'][100] = 'template/default/i_480/tv_table_focus.png';
$_MAG_DATA['gmode_480'][101] = 'template/default/i_480/mb_context_bg.png';
$_MAG_DATA['gmode_480'][102] = 'template/default/i_480/mb_filminfo_trans.png';
$_MAG_DATA['gmode_480'][103] = 'template/default/i_480/mb_icons2.png';
$_MAG_DATA['gmode_480'][104] = 'template/default/i_480/mm_menu_vert.png';
$_MAG_DATA['gmode_480'][105] = 'template/default/i_480/horoscope_menu_button_1_12_b.png';
$_MAG_DATA['gmode_480'][106] = 'template/default/i_480/mm_hor_right.png';
$_MAG_DATA['gmode_480'][107] = 'template/default/i_480/epg_green_mark.png';
$_MAG_DATA['gmode_480'][108] = 'template/default/i_480/w_rain.png';
$_MAG_DATA['gmode_480'][109] = 'template/default/i_480/v_menu_2b.png';
$_MAG_DATA['gmode_480'][110] = 'template/default/i_480/_1_moon_cl.png';
$_MAG_DATA['gmode_480'][111] = 'template/default/i_480/horoscope_menu_button_1_11_a.png';
$_MAG_DATA['gmode_480'][112] = 'template/default/i_480/footer_sidepanel.png';
$_MAG_DATA['gmode_480'][113] = 'template/default/i_480/v_menu_1a.png';
$_MAG_DATA['gmode_480'][114] = 'template/default/i_480/hr_filminfo.png';
$_MAG_DATA['gmode_480'][115] = 'template/default/i_480/horoscope_menu_button_1_5_b.png';
$_MAG_DATA['gmode_480'][116] = 'template/default/i_480/horoscope_menu_button_1_2_b.png';
$_MAG_DATA['gmode_480'][117] = 'template/default/i_480/mm_hor_bg3.png';
$_MAG_DATA['gmode_480'][118] = 'template/default/i_480/horoscope_menu_button_1_6_a.png';
$_MAG_DATA['gmode_480'][119] = 'template/default/i_480/mm_ico_ex.png';
$_MAG_DATA['gmode_480'][120] = 'template/default/i_480/item_bg.png';
$_MAG_DATA['gmode_480'][121] = 'template/default/i_480/footer_bg2.png';
$_MAG_DATA['gmode_480'][122] = 'template/default/i_480/horoscope_menu_button_1_3_a.png';
$_MAG_DATA['gmode_480'][123] = 'template/default/i_480/low_q.png';
$_MAG_DATA['gmode_480'][124] = 'template/default/i_480/8.png';
$_MAG_DATA['gmode_480'][125] = 'template/default/i_480/4.png';
$_MAG_DATA['gmode_480'][126] = 'template/default/i_480/horoscope_menu_button_1_4_b.png';
$_MAG_DATA['gmode_480'][127] = 'template/default/i_480/mm_menu_hor.png';
$_MAG_DATA['gmode_480'][128] = 'template/default/i_480/mm_ico_megogo.png';
$_MAG_DATA['gmode_480'][129] = 'template/default/i_480/footer_btn.png';
$_MAG_DATA['gmode_480'][130] = 'template/default/i_480/mb_scroll_bg.png';
$_MAG_DATA['gmode_480'][131] = 'template/default/i_480/bg.png';
$_MAG_DATA['gmode_480'][132] = 'template/default/i_480/w_snow_strong.png';
$_MAG_DATA['gmode_480'][133] = 'template/default/i_480/btn2.png';
$_MAG_DATA['gmode_480'][134] = 'template/default/i_480/mb_table_act.png';
$_MAG_DATA['gmode_480'][135] = 'template/default/i_480/prev_img.jpg';
$_MAG_DATA['gmode_480'][136] = 'template/default/i_480/mb_context_borders.png';
$_MAG_DATA['gmode_480'][137] = 'template/default/i_480/horoscope_menu_button_1_11_b.png';
$_MAG_DATA['gmode_480'][138] = 'template/default/i_480/w_sun.png';
$_MAG_DATA['gmode_480'][139] = 'template/default/i_480/_10_heavy_snow.png';
$_MAG_DATA['gmode_480'][140] = 'template/default/i_480/mb_icons.png';
$_MAG_DATA['gmode_480'][141] = 'template/default/i_480/3.png';
$_MAG_DATA['gmode_480'][142] = 'template/default/i_480/_5_rain.png';
$_MAG_DATA['gmode_480'][143] = 'template/default/i_480/mb_table_act06.png';
$_MAG_DATA['gmode_480'][144] = 'template/default/i_480/mm_ico_dm.png';
$_MAG_DATA['gmode_480'][145] = 'template/default/i_480/volume_bar.png';
$_MAG_DATA['gmode_480'][146] = 'template/default/i_480/footer_sidepanel_r.png';
$_MAG_DATA['gmode_480'][147] = 'template/default/i_480/ico_confirm.png';
$_MAG_DATA['gmode_480'][148] = 'template/default/i_480/footer_menu.png';
$_MAG_DATA['gmode_480'][149] = 'template/default/i_480/ico_info.png';
$_MAG_DATA['gmode_480'][150] = 'template/default/i_480/minus.png';
$_MAG_DATA['gmode_480'][151] = 'template/default/i_480/mm_ico_karaoke.png';
$_MAG_DATA['gmode_480'][152] = 'template/default/i_480/v_menu_2a.png';
$_MAG_DATA['gmode_480'][153] = 'template/default/i_480/_9_snow.png';
$_MAG_DATA['gmode_480'][154] = 'template/default/i_480/mm_ico_video.png';
$_MAG_DATA['gmode_480'][155] = 'template/default/i_480/footer_search_act2.png';
$_MAG_DATA['gmode_480'][156] = 'template/default/i_480/input_channel.png';
$_MAG_DATA['gmode_480'][157] = 'template/default/i_480/horoscope_menu_button_1_4_a.png';
$_MAG_DATA['gmode_480'][158] = 'template/default/i_480/w_cloud_small.png';
$_MAG_DATA['gmode_480'][159] = 'template/default/i_480/osd_time.png';
$_MAG_DATA['gmode_480'][160] = 'template/default/i_480/tv_prev_bg.png';
$_MAG_DATA['gmode_480'][161] = 'template/default/i_480/osd_line.png';
$_MAG_DATA['gmode_480'][162] = 'template/default/i_480/footer_search_act_.png';
$_MAG_DATA['gmode_480'][163] = 'template/default/i_480/horoscope_menu_button_1_7_a.png';
$_MAG_DATA['gmode_480'][164] = 'template/default/i_480/9.png';
$_MAG_DATA['gmode_480'][165] = 'template/default/i_480/pause_btn.png';
$_MAG_DATA['gmode_480'][166] = 'template/default/i_480/input_channel_bg.png';
$_MAG_DATA['gmode_480'][167] = 'template/default/i_480/mm_vert_trans.png';
$_MAG_DATA['gmode_480'][168] = 'template/default/i_480/mb_pass_bg.png';
$_MAG_DATA['gmode_480'][169] = 'template/default/i_480/mm_hor_bg2.png';
$_MAG_DATA['gmode_480'][170] = 'template/default/i_480/loading.png';
$_MAG_DATA['gmode_480'][171] = 'template/default/i_480/_4_short_rain.png';
$_MAG_DATA['gmode_480'][172] = 'template/default/i_480/v_menu_4.png';
$_MAG_DATA['gmode_480'][173] = 'template/default/i_480/arr_left.png';
$_MAG_DATA['gmode_480'][174] = 'template/default/i_480/horoscope_menu_button_1_8_b.png';
$_MAG_DATA['gmode_480'][175] = 'template/default/i_480/bg2.png';
$_MAG_DATA['gmode_480'][176] = 'template/default/i_480/mm_ico_radio.png';
$_MAG_DATA['gmode_480'][177] = 'template/default/i_480/mm_ico_vidimax.png';
$_MAG_DATA['gmode_480'][178] = 'template/default/i_480/mb_player.png';
$_MAG_DATA['gmode_480'][179] = 'template/default/i_480/_8_rain_swon.png';
$_MAG_DATA['gmode_480'][180] = 'template/default/i_480/loading_bg.gif';
$_MAG_DATA['gmode_480'][181] = 'template/default/i_480/plus.png';
$_MAG_DATA['gmode_480'][182] = 'template/default/i_480/footer_search_act.png';
$_MAG_DATA['gmode_480'][183] = 'template/default/i_480/vol_1.png';
$_MAG_DATA['gmode_480'][184] = 'template/default/i_480/mm_ico_oll.png';
$_MAG_DATA['gmode_480'][185] = 'template/default/i_480/horoscope_menu_button_1_12_a.png';
$_MAG_DATA['gmode_default'][0] = 'template/default/i/horoscope_menu_button_1_1_b.png';
$_MAG_DATA['gmode_default'][1] = 'template/default/i/footer_menu_act.png';
$_MAG_DATA['gmode_default'][2] = 'template/default/i/tv_table.png';
$_MAG_DATA['gmode_default'][3] = 'template/default/i/mb_table05.png';
$_MAG_DATA['gmode_default'][4] = 'template/default/i/mb_table07.png';
$_MAG_DATA['gmode_default'][5] = 'template/default/i/w_snow.png';
$_MAG_DATA['gmode_default'][6] = 'template/default/i/horoscope_menu_button_1_5_a.png';
$_MAG_DATA['gmode_default'][7] = 'template/default/i/mm_ico_youtube.png';
$_MAG_DATA['gmode_default'][8] = 'template/default/i/25alfa_20.png';
$_MAG_DATA['gmode_default'][9] = 'template/default/i/osd_bg.png';
$_MAG_DATA['gmode_default'][10] = 'template/default/i/_6_lightning.png';
$_MAG_DATA['gmode_default'][11] = 'template/default/i/horoscope_menu_button_1_1_a.png';
$_MAG_DATA['gmode_default'][12] = 'template/default/i/mm_ico_info.png';
$_MAG_DATA['gmode_default'][13] = 'template/default/i/horoscope_menu_button_1_7_b.png';
$_MAG_DATA['gmode_default'][14] = 'template/default/i/horoscope_menu_button_1_10_b.png';
$_MAG_DATA['gmode_default'][15] = 'template/default/i/mm_vert_cell.png';
$_MAG_DATA['gmode_default'][16] = 'template/default/i/mb_scroll.png';
$_MAG_DATA['gmode_default'][17] = 'template/default/i/mb_table06.png';
$_MAG_DATA['gmode_default'][18] = 'template/default/i/skip.png';
$_MAG_DATA['gmode_default'][19] = 'template/default/i/combobox_act.png';
$_MAG_DATA['gmode_default'][20] = 'template/default/i/mb_pass_input.png';
$_MAG_DATA['gmode_default'][21] = 'template/default/i/mm_ico_account.png';
$_MAG_DATA['gmode_default'][22] = 'template/default/i/mm_ico_tv.png';
$_MAG_DATA['gmode_default'][23] = 'template/default/i/mb_table_act04.png';
$_MAG_DATA['gmode_default'][24] = 'template/default/i/horoscope_menu_button_1_10_a.png';
$_MAG_DATA['gmode_default'][25] = 'template/default/i/w_thunderstorm.png';
$_MAG_DATA['gmode_default'][26] = 'template/default/i/mb_table04.png';
$_MAG_DATA['gmode_default'][27] = 'template/default/i/w_moon.png';
$_MAG_DATA['gmode_default'][28] = 'template/default/i/_3_pasmurno.png';
$_MAG_DATA['gmode_default'][29] = 'template/default/i/horoscope_menu_button_1_2_a.png';
$_MAG_DATA['gmode_default'][30] = 'template/default/i/v_menu_1b.png';
$_MAG_DATA['gmode_default'][31] = 'template/default/i/epg_red_mark.png';
$_MAG_DATA['gmode_default'][32] = 'template/default/i/weather.png';
$_MAG_DATA['gmode_default'][33] = 'template/default/i/mb_prev_bg.png';
$_MAG_DATA['gmode_default'][34] = 'template/default/i/aspect_bg.png';
$_MAG_DATA['gmode_default'][35] = 'template/default/i/modal_bg.png';
$_MAG_DATA['gmode_default'][36] = 'template/default/i/osd_line_pos.png';
$_MAG_DATA['gmode_default'][37] = 'template/default/i/mm_vert_border.png';
$_MAG_DATA['gmode_default'][38] = 'template/default/i/black85.png';
$_MAG_DATA['gmode_default'][39] = 'template/default/i/input.png';
$_MAG_DATA['gmode_default'][40] = 'template/default/i/input_episode_bg.png';
$_MAG_DATA['gmode_default'][41] = 'template/default/i/w_cloud_big.png';
$_MAG_DATA['gmode_default'][42] = 'template/default/i/mb_table_act05.png';
$_MAG_DATA['gmode_default'][43] = 'template/default/i/_0_moon.png';
$_MAG_DATA['gmode_default'][44] = 'template/default/i/_0_sun.png';
$_MAG_DATA['gmode_default'][45] = 'template/default/i/ico_alert.png';
$_MAG_DATA['gmode_default'][46] = 'template/default/i/ears.png';
$_MAG_DATA['gmode_default'][47] = 'template/default/i/footer_sidepanel_arr.png';
$_MAG_DATA['gmode_default'][48] = 'template/default/i/horoscope_menu_button_1_9_b.png';
$_MAG_DATA['gmode_default'][49] = 'template/default/i/w_empty.png';
$_MAG_DATA['gmode_default'][50] = 'template/default/i/mm_ico_internet.png';
$_MAG_DATA['gmode_default'][51] = 'template/default/i/mm_hor_left.png';
$_MAG_DATA['gmode_default'][52] = 'template/default/i/v_menu_5.png';
$_MAG_DATA['gmode_default'][53] = 'template/default/i/ears_arrow_l.png';
$_MAG_DATA['gmode_default'][54] = 'template/default/i/footer_sidepanel_line.png';
$_MAG_DATA['gmode_default'][55] = 'template/default/i/horoscope_menu_button_1_8_a.png';
$_MAG_DATA['gmode_default'][56] = 'template/default/i/_2_cloudy.png';
$_MAG_DATA['gmode_default'][57] = 'template/default/i/ico_error26.png';
$_MAG_DATA['gmode_default'][58] = 'template/default/i/osd_rec.png';
$_MAG_DATA['gmode_default'][59] = 'template/default/i/footer_sidepanel_l.png';
$_MAG_DATA['gmode_default'][60] = 'template/default/i/mb_quality.png';
$_MAG_DATA['gmode_default'][61] = 'template/default/i/footer_search.png';
$_MAG_DATA['gmode_default'][62] = 'template/default/i/tv_table_arrows.png';
$_MAG_DATA['gmode_default'][63] = 'template/default/i/ears_arrow_r.png';
$_MAG_DATA['gmode_default'][64] = 'template/default/i/footer_bg.png';
$_MAG_DATA['gmode_default'][65] = 'template/default/i/combobox.png';
$_MAG_DATA['gmode_default'][66] = 'template/default/i/w_cloud_black.png';
$_MAG_DATA['gmode_default'][67] = 'template/default/i/volume_off.png';
$_MAG_DATA['gmode_default'][68] = 'template/default/i/_255_NA.png';
$_MAG_DATA['gmode_default'][69] = 'template/default/i/mb_icon_rec.png';
$_MAG_DATA['gmode_default'][70] = 'template/default/i/mb_icon_scrambled.png';
$_MAG_DATA['gmode_default'][71] = 'template/default/i/arr_right.png';
$_MAG_DATA['gmode_default'][72] = 'template/default/i/footer_sidepanel_act.png';
$_MAG_DATA['gmode_default'][73] = 'template/default/i/mb_table01.png';
$_MAG_DATA['gmode_default'][74] = 'template/default/i/w_rain_strong.png';
$_MAG_DATA['gmode_default'][75] = 'template/default/i/tv_table_separator.png';
$_MAG_DATA['gmode_default'][76] = 'template/default/i/mm_ico_ivi.png';
$_MAG_DATA['gmode_default'][77] = 'template/default/i/mm_hor_bg1.png';
$_MAG_DATA['gmode_default'][78] = 'template/default/i/mm_ico_usb.png';
$_MAG_DATA['gmode_default'][79] = 'template/default/i/mm_ico_pomogator.png';
$_MAG_DATA['gmode_default'][80] = 'template/default/i/mm_ico_zoomby.png';
$_MAG_DATA['gmode_default'][81] = 'template/default/i/horoscope_menu_button_1_3_b.png';
$_MAG_DATA['gmode_default'][82] = 'template/default/i/_1_sun_cl.png';
$_MAG_DATA['gmode_default'][83] = 'template/default/i/mm_ico_tvzavr.png';
$_MAG_DATA['gmode_default'][84] = 'template/default/i/epg_orange_mark.png';
$_MAG_DATA['gmode_default'][85] = 'template/default/i/volume_bg.png';
$_MAG_DATA['gmode_default'][86] = 'template/default/i/horoscope_menu_button_1_9_a.png';
$_MAG_DATA['gmode_default'][87] = 'template/default/i/v_menu_3.png';
$_MAG_DATA['gmode_default'][88] = 'template/default/i/horoscope_menu_button_1_6_b.png';
$_MAG_DATA['gmode_default'][89] = 'template/default/i/input_act.png';
$_MAG_DATA['gmode_default'][90] = 'template/default/i/_7_hail.png';
$_MAG_DATA['gmode_default'][91] = 'template/default/i/mm_ico_setting.png';
$_MAG_DATA['gmode_default'][92] = 'template/default/i/tv_table_focus.png';
$_MAG_DATA['gmode_default'][93] = 'template/default/i/mb_context_bg.png';
$_MAG_DATA['gmode_default'][94] = 'template/default/i/mb_filminfo_trans.png';
$_MAG_DATA['gmode_default'][95] = 'template/default/i/mm_menu_vert.png';
$_MAG_DATA['gmode_default'][96] = 'template/default/i/horoscope_menu_button_1_12_b.png';
$_MAG_DATA['gmode_default'][97] = 'template/default/i/mb_table_act02.png';
$_MAG_DATA['gmode_default'][98] = 'template/default/i/mm_hor_right.png';
$_MAG_DATA['gmode_default'][99] = 'template/default/i/epg_green_mark.png';
$_MAG_DATA['gmode_default'][100] = 'template/default/i/w_rain.png';
$_MAG_DATA['gmode_default'][101] = 'template/default/i/v_menu_2b.png';
$_MAG_DATA['gmode_default'][102] = 'template/default/i/_1_moon_cl.png';
$_MAG_DATA['gmode_default'][103] = 'template/default/i/horoscope_menu_button_1_11_a.png';
$_MAG_DATA['gmode_default'][104] = 'template/default/i/footer_sidepanel.png';
$_MAG_DATA['gmode_default'][105] = 'template/default/i/v_menu_1a.png';
$_MAG_DATA['gmode_default'][106] = 'template/default/i/hr_filminfo.png';
$_MAG_DATA['gmode_default'][107] = 'template/default/i/horoscope_menu_button_1_5_b.png';
$_MAG_DATA['gmode_default'][108] = 'template/default/i/horoscope_menu_button_1_2_b.png';
$_MAG_DATA['gmode_default'][109] = 'template/default/i/mm_hor_bg3.png';
$_MAG_DATA['gmode_default'][110] = 'template/default/i/horoscope_menu_button_1_6_a.png';
$_MAG_DATA['gmode_default'][111] = 'template/default/i/mm_ico_ex.png';
$_MAG_DATA['gmode_default'][112] = 'template/default/i/item_bg.png';
$_MAG_DATA['gmode_default'][113] = 'template/default/i/footer_bg2.png';
$_MAG_DATA['gmode_default'][114] = 'template/default/i/horoscope_menu_button_1_3_a.png';
$_MAG_DATA['gmode_default'][115] = 'template/default/i/low_q.png';
$_MAG_DATA['gmode_default'][116] = 'template/default/i/horoscope_menu_button_1_4_b.png';
$_MAG_DATA['gmode_default'][117] = 'template/default/i/mm_menu_hor.png';
$_MAG_DATA['gmode_default'][118] = 'template/default/i/mm_ico_megogo.png';
$_MAG_DATA['gmode_default'][119] = 'template/default/i/footer_btn.png';
$_MAG_DATA['gmode_default'][120] = 'template/default/i/mb_scroll_bg.png';
$_MAG_DATA['gmode_default'][121] = 'template/default/i/bg.png';
$_MAG_DATA['gmode_default'][122] = 'template/default/i/w_snow_strong.png';
$_MAG_DATA['gmode_default'][123] = 'template/default/i/btn2.png';
$_MAG_DATA['gmode_default'][124] = 'template/default/i/mb_context_borders.png';
$_MAG_DATA['gmode_default'][125] = 'template/default/i/horoscope_menu_button_1_11_b.png';
$_MAG_DATA['gmode_default'][126] = 'template/default/i/w_sun.png';
$_MAG_DATA['gmode_default'][127] = 'template/default/i/_10_heavy_snow.png';
$_MAG_DATA['gmode_default'][128] = 'template/default/i/mb_icons.png';
$_MAG_DATA['gmode_default'][129] = 'template/default/i/_5_rain.png';
$_MAG_DATA['gmode_default'][130] = 'template/default/i/mb_table_act06.png';
$_MAG_DATA['gmode_default'][131] = 'template/default/i/mm_ico_dm.png';
$_MAG_DATA['gmode_default'][132] = 'template/default/i/volume_bar.png';
$_MAG_DATA['gmode_default'][133] = 'template/default/i/footer_sidepanel_r.png';
$_MAG_DATA['gmode_default'][134] = 'template/default/i/ico_confirm.png';
$_MAG_DATA['gmode_default'][135] = 'template/default/i/mb_table_act01.png';
$_MAG_DATA['gmode_default'][136] = 'template/default/i/footer_menu.png';
$_MAG_DATA['gmode_default'][137] = 'template/default/i/ico_info.png';
$_MAG_DATA['gmode_default'][138] = 'template/default/i/mm_ico_karaoke.png';
$_MAG_DATA['gmode_default'][139] = 'template/default/i/v_menu_2a.png';
$_MAG_DATA['gmode_default'][140] = 'template/default/i/_9_snow.png';
$_MAG_DATA['gmode_default'][141] = 'template/default/i/mb_table_act03.png';
$_MAG_DATA['gmode_default'][142] = 'template/default/i/mm_ico_video.png';
$_MAG_DATA['gmode_default'][143] = 'template/default/i/footer_search_act2.png';
$_MAG_DATA['gmode_default'][144] = 'template/default/i/input_channel.png';
$_MAG_DATA['gmode_default'][145] = 'template/default/i/horoscope_menu_button_1_4_a.png';
$_MAG_DATA['gmode_default'][146] = 'template/default/i/w_cloud_small.png';
$_MAG_DATA['gmode_default'][147] = 'template/default/i/osd_time.png';
$_MAG_DATA['gmode_default'][148] = 'template/default/i/tv_prev_bg.png';
$_MAG_DATA['gmode_default'][149] = 'template/default/i/osd_line.png';
$_MAG_DATA['gmode_default'][150] = 'template/default/i/horoscope_menu_button_1_7_a.png';
$_MAG_DATA['gmode_default'][151] = 'template/default/i/mb_table03.png';
$_MAG_DATA['gmode_default'][152] = 'template/default/i/pause_btn.png';
$_MAG_DATA['gmode_default'][153] = 'template/default/i/input_channel_bg.png';
$_MAG_DATA['gmode_default'][154] = 'template/default/i/mm_vert_trans.png';
$_MAG_DATA['gmode_default'][155] = 'template/default/i/mb_pass_bg.png';
$_MAG_DATA['gmode_default'][156] = 'template/default/i/mm_hor_bg2.png';
$_MAG_DATA['gmode_default'][157] = 'template/default/i/loading.png';
$_MAG_DATA['gmode_default'][158] = 'template/default/i/_4_short_rain.png';
$_MAG_DATA['gmode_default'][159] = 'template/default/i/v_menu_4.png';
$_MAG_DATA['gmode_default'][160] = 'template/default/i/arr_left.png';
$_MAG_DATA['gmode_default'][161] = 'template/default/i/horoscope_menu_button_1_8_b.png';
$_MAG_DATA['gmode_default'][162] = 'template/default/i/mb_table02.png';
$_MAG_DATA['gmode_default'][163] = 'template/default/i/bg2.png';
$_MAG_DATA['gmode_default'][164] = 'template/default/i/mm_ico_radio.png';
$_MAG_DATA['gmode_default'][165] = 'template/default/i/mm_ico_vidimax.png';
$_MAG_DATA['gmode_default'][166] = 'template/default/i/mb_player.png';
$_MAG_DATA['gmode_default'][167] = 'template/default/i/_8_rain_swon.png';
$_MAG_DATA['gmode_default'][168] = 'template/default/i/loading_bg.gif';
$_MAG_DATA['gmode_default'][169] = 'template/default/i/footer_search_act.png';
$_MAG_DATA['gmode_default'][170] = 'template/default/i/mm_ico_oll.png';
$_MAG_DATA['gmode_default'][171] = 'template/default/i/horoscope_menu_button_1_12_a.png';
$_MAG_DATA['settings_array'] = [
	'js' => [
		'modules' => [
			['name' => 'lock'],
			['name' => 'lang'],
			['name' => 'update'],
			[
				'name' => 'net_info',
				'sub'  => [
					['name' => 'wired'],
					[
						'name' => 'pppoe',
						'sub'  => [
							['name' => 'dhcp'],
							['name' => 'dhcp_manual'],
							['name' => 'disable']
						]
					],
					['name' => 'wireless'],
					['name' => 'speed']
				]
			],
			['name' => 'video'],
			['name' => 'audio'],
			[
				'name' => 'net',
				'sub'  => [
					[
						'name' => 'ethernet',
						'sub'  => [
							['name' => 'dhcp'],
							['name' => 'dhcp_manual'],
							['name' => 'manual'],
							['name' => 'no_ip']
						]
					],
					[
						'name' => 'pppoe',
						'sub'  => [
							['name' => 'dhcp'],
							['name' => 'dhcp_manual'],
							['name' => 'disable']
						]
					],
					[
						'name' => 'wifi',
						'sub'  => [
							['name' => 'dhcp'],
							['name' => 'dhcp_manual'],
							['name' => 'manual']
						]
					]
				]
			],
			['name' => 'advanced'],
			['name' => 'dev_info'],
			['name' => 'reload'],
			['name' => 'internal_portal'],
			['name' => 'reboot']
		]
	]
];
$_MAG_DATA['get_locales']['English'] = 'en_GB.utf8';
$_MAG_DATA['all_modules'] = ['media_browser', 'tv', 'apps', 'dvb', 'tv_archive', 'time_shift', 'time_shift_local', 'epg.reminder', 'epg.recorder', 'epg', 'epg.simple', 'vclub', 'youtube', 'karaoke', 'radio', 'records', 'remotepvr', 'pvr_local', 'settings.parent', 'settings.localization', 'settings.update', 'settings.playback', 'settings.common', 'settings.network_status', 'game.lines', 'game.memory', 'game.sudoku', 'picasa', 'settings', 'weather.weatherco.day', 'cityinfo', 'internet'];
$_MAG_DATA['switchable_modules'] = ['karaoke', 'weather.day', 'cityinfo', 'horoscope', 'horoscope', 'anecdote', 'game.mastermind', 'infoportal'];
$_MAG_DATA['disabled_modules'] = ['weather.weatherco.day', 'picasa', 'remotepvr', 'settings.update', 'settings.common', 'pvr_local', 'game.lines', 'game.memory', 'game.sudoku', 'karaoke', 'weather.day', 'cityinfo', 'horoscope', 'anecdote', 'game.mastermind', 'infoportal'];
$_MAG_DATA['restricted_modules'] = [];
$_MAG_DATA['template'] = 'default';
$_MAG_DATA['get_years'] = [
	'js' => [
		['id' => '*', 'title' => '*'],
		['id' => '1937', 'title' => '1937'],
		['id' => '1940', 'title' => '1940'],
		['id' => '1941', 'title' => '1941'],
		['id' => '1951', 'title' => '1951'],
		['id' => '1953', 'title' => '1953'],
		['id' => '1955', 'title' => '1955'],
		['id' => '1961', 'title' => '1961'],
		['id' => '1964', 'title' => '1964'],
		['id' => '1970', 'title' => '1970'],
		['id' => '1983', 'title' => '1983'],
		['id' => '1986', 'title' => '1986'],
		['id' => '1990', 'title' => '1990'],
		['id' => '1992', 'title' => '1992'],
		['id' => '1994', 'title' => '1994'],
		['id' => '1994/1998/2004', 'title' => '1994/1998/2004'],
		['id' => '1995', 'title' => '1995'],
		['id' => '1995/1999/2010', 'title' => '1995/1999/2010'],
		['id' => '1996', 'title' => '1996'],
		['id' => '1998', 'title' => '1998'],
		['id' => '1999', 'title' => '1999'],
		['id' => '2000', 'title' => '2000'],
		['id' => '2001', 'title' => '2001'],
		['id' => '2002', 'title' => '2002'],
		['id' => '2003', 'title' => '2003'],
		['id' => '2004', 'title' => '2004'],
		['id' => '2005', 'title' => '2005'],
		['id' => '2006', 'title' => '2006'],
		['id' => '2007', 'title' => '2007'],
		['id' => '2008', 'title' => '2008'],
		['id' => '2009', 'title' => '2009'],
		['id' => '2010', 'title' => '2010'],
		['id' => '2011', 'title' => '2011'],
		['id' => '2012', 'title' => '2012'],
		['id' => '2013', 'title' => '2013'],
		['id' => '2013', 'title' => '2013'],
		['id' => '2014', 'title' => '2014']
	]
];
$_MAG_DATA['get_abc'] = [
	'js' => [
		['id' => '*', 'title' => '*'],
		['id' => 'A', 'title' => 'A'],
		['id' => 'B', 'title' => 'B'],
		['id' => 'C', 'title' => 'C'],
		['id' => 'D', 'title' => 'D'],
		['id' => 'E', 'title' => 'E'],
		['id' => 'F', 'title' => 'F'],
		['id' => 'G', 'title' => 'G'],
		['id' => 'H', 'title' => 'H'],
		['id' => 'I', 'title' => 'I'],
		['id' => 'G', 'title' => 'G'],
		['id' => 'K', 'title' => 'K'],
		['id' => 'L', 'title' => 'L'],
		['id' => 'M', 'title' => 'M'],
		['id' => 'N', 'title' => 'N'],
		['id' => 'O', 'title' => 'O'],
		['id' => 'P', 'title' => 'P'],
		['id' => 'Q', 'title' => 'Q'],
		['id' => 'R', 'title' => 'R'],
		['id' => 'S', 'title' => 'S'],
		['id' => 'T', 'title' => 'T'],
		['id' => 'U', 'title' => 'U'],
		['id' => 'V', 'title' => 'V'],
		['id' => 'W', 'title' => 'W'],
		['id' => 'X', 'title' => 'X'],
		['id' => 'W', 'title' => 'W'],
		['id' => 'Z', 'title' => 'Z']
	]
];

?>